"""Type stubs for pynest2d — Python bindings for libnest2d.

Comprehensive 2D bin packing / polygon nesting with three placer+selector combos:
  nest()      — NFP placer  + FirstFit selection  (default, general-purpose)
  nest_blp()  — Bottom-Left + FirstFit selection  (simpler, faster)
  nest_djd()  — NFP placer  + DJD heuristic       (slower, better packing)
"""

from __future__ import annotations
from typing import Callable, List, Optional, overload

# ── MARK: Constants ────────────────────────────────────────────────────────
MM_IN_COORDS: int
"""Internal coordinate units per millimeter (1 000 000 for Clipper backend)."""
BIN_ID_UNSET: int
"""Sentinel value for unplaced items (-1)."""

# ── MARK: Point ────────────────────────────────────────────────────────────
class Point:
    """2D integer coordinate (Clipper IntPoint)."""
    def __init__(self, x: int, y: int) -> None: ...
    def x(self) -> int: ...
    def y(self) -> int: ...
    def setX(self, x: int) -> None: ...
    def setY(self, y: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...

# ── MARK: Box ──────────────────────────────────────────────────────────────
class Box:
    """Axis-aligned rectangular bin."""
    @overload
    def __init__(self, width: int, height: int) -> None: ...
    @overload
    def __init__(self, width: int, height: int, center: Point) -> None: ...
    def width(self) -> int: ...
    def height(self) -> int: ...
    def center(self) -> Point: ...
    def minCorner(self) -> Point: ...
    def maxCorner(self) -> Point: ...
    def area(self) -> float: ...
    @staticmethod
    def infinite(center: Point = ...) -> Box:
        """Create a near-infinite box around a center point."""
        ...
    def __repr__(self) -> str: ...

# ── MARK: Circle ──────────────────────────────────────────────────────────
class Circle:
    """Circle shape (center + radius)."""
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, center: Point, radius: float) -> None: ...
    def center(self) -> Point: ...
    def setCenter(self, center: Point) -> None: ...
    def radius(self) -> float: ...
    def setRadius(self, radius: float) -> None: ...
    def area(self) -> float: ...
    def __repr__(self) -> str: ...

# ── MARK: Segment ─────────────────────────────────────────────────────────
class Segment:
    """Directed line segment."""
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p1: Point, p2: Point) -> None: ...
    def first(self) -> Point: ...
    def second(self) -> Point: ...
    def setFirst(self, p: Point) -> None: ...
    def setSecond(self, p: Point) -> None: ...
    def angleToXaxis(self) -> float: ...
    def sqlength(self) -> float:
        """Squared length (double precision)."""
        ...
    def __repr__(self) -> str: ...

# ── MARK: Orientation enum ────────────────────────────────────────────────
class Orientation:
    """Polygon winding orientation."""
    CLOCKWISE: Orientation
    COUNTER_CLOCKWISE: Orientation

# ── MARK: Alignment enum ──────────────────────────────────────────────────
class Alignment:
    """NFP placer alignment mode."""
    CENTER: Alignment
    BOTTOM_LEFT: Alignment
    BOTTOM_RIGHT: Alignment
    TOP_LEFT: Alignment
    TOP_RIGHT: Alignment
    DONT_ALIGN: Alignment

# ── MARK: NfpConfig ───────────────────────────────────────────────────────
class NfpConfig:
    """Configuration for the NFP placer (default: 4 rotations, CENTER alignment)."""
    def __init__(self) -> None: ...
    alignment: Alignment
    starting_point: Alignment
    rotations: list[float]
    accuracy: float
    explore_holes: bool
    parallel: bool
    object_function: Optional[Callable[[Item], float]]
    """Custom scoring function evaluated during placement optimization."""

# ── MARK: BLConfig ────────────────────────────────────────────────────────
class BLConfig:
    """Configuration for the Bottom-Left placer."""
    def __init__(self) -> None: ...
    min_obj_distance: int
    epsilon: int
    allow_rotations: bool

# ── MARK: DJDConfig ───────────────────────────────────────────────────────
class DJDConfig:
    """Configuration for the DJD (Dyckhoff) heuristic selector."""
    def __init__(self) -> None: ...
    try_reverse_order: bool
    try_pairs: bool
    try_triplets: bool
    initial_fill_proportion: float
    waste_increment: float
    allow_parallel: bool
    force_parallel: bool

# ── MARK: NestControl ────────────────────────────────────────────────────
class NestControl:
    """Progress / stop callbacks for nest()."""
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, progress: Callable[[int], None]) -> None: ...
    @overload
    def __init__(self, stop: Callable[[], bool]) -> None: ...
    @overload
    def __init__(self, progress: Callable[[int], None], stop: Callable[[], bool]) -> None: ...
    progress: Optional[Callable[[int], None]]
    stop: Optional[Callable[[], bool]]

# ── MARK: Item ────────────────────────────────────────────────────────────
class Item:
    """A polygonal item to be packed."""
    @overload
    def __init__(self, vertices: List[Point]) -> None:
        """Create from contour vertices (no holes)."""
        ...
    @overload
    def __init__(self, contour: List[Point], holes: List[List[Point]]) -> None:
        """Create from contour + hole rings."""
        ...
    # Placement state
    def binId(self) -> int: ...
    def setBinId(self, id: int) -> None: ...
    def isFixed(self) -> bool: ...
    def markAsFixedInBin(self, binid: int) -> None: ...
    def priority(self) -> int: ...
    def setPriority(self, priority: int) -> None: ...
    # Geometry queries
    def vertexCount(self) -> int: ...
    def vertex(self, idx: int) -> Point: ...
    def setVertex(self, idx: int, v: Point) -> None: ...
    def holeCount(self) -> int: ...
    def area(self) -> float: ...
    def isContourConvex(self) -> bool: ...
    def isHoleConvex(self, holeidx: int) -> bool: ...
    def areHolesConvex(self) -> bool: ...
    def boundingBox(self) -> Box: ...
    # Reference vertices
    def rightmostTopVertex(self) -> Point: ...
    def leftmostBottomVertex(self) -> Point: ...
    def referenceVertex(self) -> Point: ...
    # Containment
    def isInside(self, point: Point) -> bool: ...
    def isInsideItem(self, other: Item) -> bool: ...
    def isInsideBox(self, box: Box) -> bool: ...
    def isInsideCircle(self, circle: Circle) -> bool: ...
    # Static collision checks
    @staticmethod
    def intersects(a: Item, b: Item) -> bool: ...
    @staticmethod
    def touches(a: Item, b: Item) -> bool: ...
    @staticmethod
    def orientation() -> Orientation: ...
    # Transformations
    def translate(self, delta: Point) -> None: ...
    def translation(self) -> Point: ...
    def setTranslation(self, p: Point) -> None: ...
    def rotate(self, radians: float) -> None: ...
    def rotation(self) -> float: ...
    def setRotation(self, radians: float) -> None: ...
    def inflation(self) -> int: ...
    def setInflation(self, distance: int) -> None: ...
    def inflate(self, distance: int) -> None:
        """Increase inflation by delta (cumulative)."""
        ...
    def resetTransformation(self) -> None: ...
    # Transformed geometry (authoritative placement result)
    def transformedContour(self) -> List[Point]: ...
    def transformedHoles(self) -> List[List[Point]]: ...
    # Raw (untransformed) geometry
    def rawContour(self) -> List[Point]: ...
    def rawHoles(self) -> List[List[Point]]: ...
    # String repr
    def toString(self) -> str: ...
    def __repr__(self) -> str: ...

# ── MARK: Rectangle ──────────────────────────────────────────────────────
class Rectangle(Item):
    """Convenience subclass of Item for rectangular shapes."""
    def __init__(self, width: int, height: int) -> None: ...
    def width(self) -> int: ...
    def height(self) -> int: ...

# ── MARK: nest() — NFP + FirstFit ────────────────────────────────────────
def nest(
    items: List[Item],
    bin: Box,
    distance: int = 0,
    config: NfpConfig = ...,
    control: NestControl = ...,
) -> int:
    """Pack items using NFP placer + first-fit selection.

    Args:
        items: List of Item instances to pack (modified in-place).
        bin: Box defining bin dimensions.
        distance: Minimum spacing between items (default 0).
        config: NfpConfig placer options.
        control: NestControl with optional progress/stop callbacks.

    Returns:
        Number of bins used.
    """
    ...

# ── MARK: nest_blp() — Bottom-Left + FirstFit ────────────────────────────
def nest_blp(
    items: List[Item],
    bin: Box,
    distance: int = 0,
    config: BLConfig = ...,
    control: NestControl = ...,
) -> int:
    """Pack items using bottom-left placer + first-fit selection."""
    ...

# ── MARK: nest_djd() — NFP + DJD Heuristic ──────────────────────────────
def nest_djd(
    items: List[Item],
    bin: Box,
    distance: int = 0,
    placer_config: NfpConfig = ...,
    selector_config: DJDConfig = ...,
    control: NestControl = ...,
) -> int:
    """Pack items using NFP placer + DJD heuristic selection (slower, better packing)."""
    ...

# ── MARK: mm() — unit conversion ─────────────────────────────────────────
def mm(val: float = 1.0) -> int:
    """Convert millimeters to libnest2d internal coordinate units."""
    ...
