"""Type stubs for pynest2d — Python bindings for libnest2d."""

from __future__ import annotations
from typing import List, overload

class Point:
    """2D integer coordinate (Clipper IntPoint)."""
    def __init__(self, x: int, y: int) -> None: ...
    def x(self) -> int: ...
    def y(self) -> int: ...

class Box:
    """Axis-aligned rectangular bin."""
    @overload
    def __init__(self, width: int, height: int) -> None: ...
    @overload
    def __init__(self, width: int, height: int, center: Point) -> None: ...
    def width(self) -> int: ...
    def height(self) -> int: ...
    def center(self) -> Point: ...
    def area(self) -> float: ...

class Alignment:
    """NFP placer alignment mode."""
    CENTER: Alignment
    BOTTOM_LEFT: Alignment
    BOTTOM_RIGHT: Alignment
    TOP_LEFT: Alignment
    TOP_RIGHT: Alignment
    DONT_ALIGN: Alignment

class NfpConfig:
    """Configuration for the NFP placer algorithm."""
    def __init__(self) -> None: ...
    alignment: Alignment
    starting_point: Alignment
    rotations: list[float]
    accuracy: float
    explore_holes: bool
    parallel: bool

class Item:
    """A polygonal item to be packed."""
    def __init__(self, vertices: List[Point]) -> None: ...
    # Placement state
    def binId(self) -> int: ...
    def setBinId(self, id: int) -> None: ...
    def isFixed(self) -> bool: ...
    def markAsFixedInBin(self, binid: int) -> None: ...
    def priority(self) -> int: ...
    def setPriority(self, priority: int) -> None: ...
    # Geometry queries
    def vertexCount(self) -> int: ...
    def vertex(self, idx: int) -> Point: ...
    def holeCount(self) -> int: ...
    def area(self) -> float: ...
    def isContourConvex(self) -> bool: ...
    def boundingBox(self) -> Box: ...
    # Containment
    def isInside(self, p: Point) -> bool: ...
    # Transformations
    def translate(self, delta: Point) -> None: ...
    def translation(self) -> Point: ...
    def setTranslation(self, p: Point) -> None: ...
    def rotate(self, radians: float) -> None: ...
    def rotation(self) -> float: ...
    def setRotation(self, radians: float) -> None: ...
    def inflation(self) -> int: ...
    def setInflation(self, distance: int) -> None: ...
    def transformedShape(self) -> object: ...
    def resetTransformation(self) -> None: ...
    def toString(self) -> str: ...

def nest(
    items: List[Item],
    bin: Box,
    distance: int = 0,
    config: NfpConfig = ...,
) -> int:
    """Arrange items in bins using NFP (No-Fit-Polygon) placement.

    Args:
        items: List of Item instances to pack.
        bin: Box defining the bin dimensions.
        distance: Minimum spacing between items. Default 0.
        config: NfpConfig for placer options.

    Returns:
        Number of bins required to fit all items.
    """
    ...
